[package]
name = "lsm-btree-db"
version = "0.0.1"
edition = "2025"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = ""
tokio = { version = "1.0", features = ["full"] }
thiserror = ""
futures = ""
async-trait = ""
lsm-tree = "2.10"